/*
 * Copyright 2023-2025 Cyface GmbH
 *
 * This file is part of the Cyface SDK for Android.
 *
 * The Cyface SDK for Android is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * The Cyface SDK for Android is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the Cyface SDK for Android. If not, see <http://www.gnu.org/licenses/>.
 */
package de.cyface.persistence.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey
import de.cyface.protos.model.File.FileType
import java.nio.file.Path

/**
 * An `@Entity` which represents a persisted [ParcelableAttachment], usually captured by a camera.
 *
 * An instance of this class represents one row in a database table containing the file reference.
 *
 * We hat to decouple [Attachment] from [ParcelableAttachment] as `fileFormatVersion` was `0` in
 * the superclass `init` block with Kotlin (after an upgrade) and Room w/ksp (just switched). This
 * should anyway be cleaner, as parcel is for capturing and the entity for the persistence layer.
 *
 * @author Armin Schnabel
 * @version 2.0.0
 * @since 7.10.0
 * @property id The system-wide unique identifier of this entity, generated by the data store.
 * It's `0`, which equals `null` in the non-nullable column `Long` when the entry is not yet persisted.
 * @property measurementId The device-unique id of the measurement this data point belongs to.
 * @property timestamp The time at this data point was captured in milliseconds since 1.1.1970.
 * @property status The status of the [Attachment].
 * @property type The type of the file, e.g. JPG (compressed image).
 * @property fileFormatVersion The file format version of this data point, e.g. 1.
 * @property size The size of the file represented by this data point in bytes.
 * @property path The path to the file represented by this data point.
 * The path is by default relative to the app-specific external storage directory defined
 * by Android: https://developer.android.com/training/data-storage/app-specific
 * @property lat The latitude of the last known location, e.g. 51.123, or null if unknown.
 * @property lon The longitude of the last known location, e.g. 13.123, or null if unknown.
 * @property locationTimestamp The timestamp of the last known location, or null if unknown.
 * @property measurementId The device-unique id of the measurement this data point belongs to.
 * This foreign key points to [Measurement.id] and is indexed to avoid full table scan on parent update.
 */
@Entity(
    // Keep the table schema in sync with [de.cyface.persistence.content.AttachmentTable]
    foreignKeys = [ForeignKey(
        entity = Measurement::class,
        parentColumns = arrayOf("_id"),
        childColumns = arrayOf("measurementId"),
        onDelete = ForeignKey.CASCADE
    )]
)
data class Attachment(
    @ColumnInfo(name = "_id") // The CursorAdapter requires a column with the name `_id`
    @PrimaryKey(autoGenerate = true)
    var id: Long = 0,
    val timestamp: Long,
    val status: AttachmentStatus,
    val type: FileType,
    val fileFormatVersion: Short,
    val size: Long,
    val path: Path,
    val lat: Double?,
    val lon: Double?,
    val locationTimestamp: Long?,
    @ColumnInfo(index = true)
    val measurementId: Long,
) {
    /**
     * Creates a new instance of this class which was not yet persisted and has [id] set to `0`.
     *
     * @param attachment The cached [ParcelableAttachment] to create the [Attachment] from.
     * @param measurementId The device-unique id of the measurement this data point belongs to.
     */
    constructor(attachment: ParcelableAttachment, measurementId: Long) : this(
        id = 0,
        timestamp = attachment.timestamp,
        status = attachment.status,
        type = attachment.type,
        fileFormatVersion = attachment.fileFormatVersion,
        size = attachment.size,
        path = attachment.path,
        lat = attachment.lat,
        lon = attachment.lon,
        locationTimestamp = attachment.locationTimestamp,
        measurementId = measurementId,
    )

    init {
        require(timestamp >= 0L) { "Illegal argument: timestamp was less than 0L!" }
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Attachment

        if (id != other.id) return false
        if (timestamp != other.timestamp) return false
        if (status != other.status) return false
        if (type != other.type) return false
        if (fileFormatVersion != other.fileFormatVersion) return false
        if (size != other.size) return false
        if (path != other.path) return false
        if (lat != other.lat) return false
        if (lon != other.lon) return false
        if (locationTimestamp != other.locationTimestamp) return false
        if (measurementId != other.measurementId) return false

        return true
    }

    override fun hashCode(): Int {
        return id.hashCode()
    }
}
