# This workflow ensures the building step works
#
# @author Armin Schnabel
# @version 1.1.0
# @since 5.0.0
name: Gradle Build

on:
  push:
    branches:
      - 'release-6'
  pull_request:
    branches:
      - 'release-6'

jobs:
  build:
    runs-on: macos-latest # See `actions/android-emulator-runner`

    # To test against multiple APIs
    strategy:
      matrix:
        api-level: [ 28 ]
        target: [ default ] # e.g. [default, google_apis]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create empty truststore file
        run: |
          # When no truststore is required by the server we create an empty file or else the build fails
          mkdir -p synchronization/src/main/res/raw
          touch synchronization/src/main/res/raw/truststore.jks

      - name: Add gradle.properties
        run: |
          # Use a personal read token to install the Cyface Utils package
          cp gradle.properties.template gradle.properties
          echo "githubUser=${{ secrets.GH_READ_ACCOUNT }}" >> gradle.properties
          echo "githubToken=${{ secrets.GH_READ_TOKEN }}" >> gradle.properties
      - name: Build with Gradle
        run: ./gradlew build

      # Only execute mock tests to exclude `@FlakyTest`s (instead of running `connectedCheck`)
      - name: Connected persistence tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          script: ./gradlew :persistence:connectedDebugAndroidTest
      - name: Connected datacapturing tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          script: ./gradlew :datacapturing:connectedCyfaceMockDebugAndroidTest :datacapturing:connectedMovebisMockDebugAndroidTest
      - name: Connected synchronization tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          script: ./gradlew :synchronization:connectedCyfaceMockDebugAndroidTest :synchronization:connectedMovebisMockDebugAndroidTest
