# This workflow ensures the building step works
#
# @author Armin Schnabel
# @version 1.0.3
# @since 5.0.0
name: Gradle Build

on:
  push:
    branches:
      - 'release-6'
  pull_request:
    branches:
      - 'release-6'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create empty truststore file
        run: |
          # When no truststore is required by the server we create an empty file or else the build fails
          mkdir -p synchronization/src/main/res/raw
          touch synchronization/src/main/res/raw/truststore.jks

      - name: Add gradle.properties
        run: |
          # Use a personal read token to install the Cyface Utils package
          cp gradle.properties.template gradle.properties
          echo "githubUser=${{ secrets.GH_READ_ACCOUNT }}" >> gradle.properties
          echo "githubToken=${{ secrets.GH_READ_TOKEN }}" >> gradle.properties

      # Executing build here on Ubuntu stack (1/10th costs of MacOS stack)
      - name: Build with Gradle
        run: ./gradlew build
