# This workflow runs the building steps and tests
#
# @author Armin Schnabel
# @version 2.0.0
# @since 5.0.0
name: Gradle Build

on:
  push:
    branches:
      - 'release-6'
  pull_request:
    branches:
      - 'release-6'

jobs:
  build:
    runs-on: macos-latest # See `actions/android-emulator-runner`

    # To test against multiple APIs
    strategy:
      matrix:
        api-level: [ 28 ]
        target: [ default ] # e.g. [default, google_apis]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Create empty truststore file
        run: |
          # When no truststore is required by the server we create an empty file or else the build fails
          mkdir -p synchronization/src/main/res/raw
          touch synchronization/src/main/res/raw/truststore.jks

      - name: Add gradle.properties
        run: |
          # Use a personal read token to install the Cyface Utils package
          cp gradle.properties.template gradle.properties
          echo "githubUser=${{ secrets.GH_READ_ACCOUNT }}" >> gradle.properties
          echo "githubToken=${{ secrets.GH_READ_TOKEN }}" >> gradle.properties

      # FIXME
      #- name: Build with Gradle
      #  run: ./gradlew build

      # Add caching to speed up connected tests below (see `actions/android-emulator-runner`)
      - name: Gradle cache
        uses: gradle/gradle-build-action@v2
      - name: AVD cache
        uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}
      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      # Only execute mock tests to exclude `@FlakyTest`s (instead of running `connectedCheck`)
      - name: Connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          force-avd-creation: false # speedup
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none # speedup
          disable-animations: true # speedup
          script: ./gradlew :persistence:connectedDebugAndroidTest :datacapturing:connectedCyfaceMockDebugAndroidTest :synchronization:connectedCyfaceMockDebugAndroidTest :datacapturing:connectedMovebisMockDebugAndroidTest :synchronization:connectedMovebisMockDebugAndroidTest
